# Site settings
title: Manu Srinath Halvagal
email: mshalvagal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is a webpage I thought would be useful to share some of my work and interests.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.com" # the base hostname & protocol for your site
github_username:  mshalvagal

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Undergraduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
